---
title: "In-class_Ex02"
author: "ZHANG Jinghan"
---

```  {r}       
install.packages("maptools",repos = "https://packagemanager.posit.co/cran/2023-10-13")
```
#把好几个图的信息重叠在一起 st_union
```{r}
sg_sf <-mpsz_sf %>%
  st_union
```

```{r}
gridded_kde_childcareSG_an <- as(
  kde_childcareSG_adaptive,
  "spatialGridDataFrame"
)
spplot(gridded_kde_childcareSG_ad)
```
#后面的经纬度有NA，不filter掉跑不动
```{r}
rdacc_sf <- read_csv("C:/JinghanZzz/ISSS608-VAA/In-class_Ex/In-class_Ex02/data/thai_road_accident_2019_2022.csv") %>%
  filter(!is.na(longitude) & longitude != "",
         !is.na(latitude) & latitude != "") %>%
  st_as_sf(coords = c("longitude", "latitude"),
           crs = 4326) %>%
  st_transform(crs = 32647)   #早点做st transformation，不然后面都是小数
```

rdacc_sf <- read_csv("data/thai_road_accident_2019_2022.csv") %>%
  filter(!is.na(longitude) & longitude != "",
         !is.na(latitude) & latitude != "") %>%
  st_as_sf(coords = c("longitude", "latitude"),
           crs = 4326) %>%
  st_transform(crs = 32647)


```{r}

```

```{r}

```

```{r}

```

```{r}

```
